### PR TITLE
Add setup instructions for read only plugin, refs #69

### PR DESCRIPTION
**Pull request by La0**

### CODE REVIEW

**Comment by klahnakoski** [comment]
Will the ActiveData service be blocked with this config?  Can this still be behind nginx?   Should this have its own node, maybe its own docker image, like as tested?

**Comment by La0** [comment]
With this configuration, everything is allowed on localhost, so ActiveData should be fine as its gunicorn process queries on localhost (right ?).
This plugin is only needed on the frontend (or any other instance publicly exposed).

It should work as-is behing an Nginx server, but i do not recommend to add another layer in front of this server.

It could also run on another server, on docker or bare-metal, but must be included in the cluster (of course !)

**Comment by klahnakoski** [comment]
Thinking more, given the number of moving parts, I am tending toward a separate machine holding this endpoint; which can be deployed without shutting down the frontend node.

**Comment by klahnakoski** [comment]
The TUID project has its own node, so complications and crashes are isolated to itself.

https://github.com/mozilla/TUID/blob/dev/resources/scripts/setup_server.sh

@La0 How much drivespace would you need on a standalone machine?  The node will not store data, so the ES only needs space for logging.

**Comment by La0** [comment]
@klahnakoski No problem for using the TUID project, as long as the server has access to the `codecoverage` and `repo` indexes.

The server should not need any data except for logs, and storing the plugin during install (14 Mb)

**Comment by klahnakoski** [comment]
@La0, when you have the machine working, please link the setup script here, or put the script in `/resources/scripts/setup_es_codecoverage_t2.small.sh`, or something like that

**Comment by klahnakoski** [comment]
Sorry for the delay, I must not be getting notifications from this repo.  

This looks fine to me

**Pull request merged**
